web-beginner-en-ZQQ64/0/7
Visit: http://www.codecademy.com/es/courses/web-beginner-en-ZQQ64/0/7
Browser Internet Explorer 10, Versión: 10.0.9200.16721

it say "way to go", even if you do it wrong, when i was typing the code,
i did made a mistake clicking on "save & submit code", and at that time
i do not completed the exercise, i did not write the code for function
"bark()", and also typed wrong on the function construct because i didnt
declare the var numlegs and use it in the function, and in the function
greet i didnt put the "$" to the "this", and the preview say "Parse
error: syntax error, unexpected T_OBJECT_OPERATOR on line 25 ", below is
the bad code